"""AI market briefing — a cross-asset desk note generated by Claude from the day's news.

Oil and refined products are the firm's core focus, but the brief covers the full picture
Neil needs: macro, geopolitics, energy/fuel, reserves & inventories, and big market movers
(e.g. a megacap selling off and dragging an index). Feeds Claude a categorized headline
set + live prices, spreads, broad-market movers and EIA inventories, and asks for a sharp
sectioned briefing. Stored to data/brief.json so the dashboard/email can show it without
re-calling the API on every load.

Requires ANTHROPIC_API_KEY (env or .env). Uses the cost-effective Haiku tier by default.
"""

import json
from datetime import datetime, timezone
from typing import Dict, List

from . import DATA_DIR
from .llm_sentiment import MODEL, available  # reuse key detection + default model

BRIEF_PATH = DATA_DIR / "brief.json"

# Category -> display label + order in the prompt's headline dump. Drives the news context
# we hand Claude; the model decides which sections actually warrant words.
_CATEGORY_LABELS = [
    ("energy", "ENERGY & FUEL"),
    ("commodities", "COMMODITIES"),
    ("geopolitics", "GEOPOLITICAL"),
    ("macro", "MACRO / RATES / FX"),
    ("markets", "MARKETS / EQUITIES"),
    ("shipping", "SHIPPING / LOGISTICS"),
    ("social", "SOCIAL / OFFICIALS"),
    ("weather", "WEATHER"),
]
_PER_CATEGORY = 9  # cap headlines per category so no single bucket dominates the prompt

_SYSTEM = (
    "You are the chief market strategist at Sheerstock Park, an oil-trading firm, writing the "
    "{edition} market briefing for the principal. Crude and refined products are the core book, "
    "but he needs the whole cross-asset tape: anything moving oil, energy or the broader markets.\n\n"
    "VOICE — write like a senior trader briefing the desk: terse, concrete, confident. Desk jargon "
    "is welcome (bid, offered, gapped, risk-off, backwardation, bear-flattener). Always give the "
    "READ — direction, level, and why it matters. No hedging, no filler, no 'could potentially'. "
    "Use ONLY the prices, inventories and headlines provided; never invent numbers.\n\n"
    "FORMAT — clean GitHub-flavored Markdown. Each section is a bold header exactly as written "
    "below. Every bullet is HEADLINE-STYLE: a **bold punchy headline** then ' — ' then a one-line "
    "trader read ending in the bullish/bearish call. Lead with the biggest stories. OMIT any "
    "section with nothing material — a short sharp brief beats a padded one.\n\n"
    "SECTIONS, in this exact order:\n"
    "**📰 Top Headlines** — the 3-4 most market-moving stories of the session, headline-first, each "
    "with the immediate trade read. This is the hero — make it punchy and scannable.\n"
    "**🛢 Energy & Fuel** — crude, products, refining margins, demand. The core book.\n"
    "**🌍 Geopolitics** — conflict, sanctions, OPEC+ politics, supply routes (Hormuz, Red Sea).\n"
    "**📊 Macro & Rates** — rates, inflation, central banks, the dollar, growth — and the risk read.\n"
    "**📈 Market Movers** — big equity / index / cross-asset moves; name the largest movers.\n"
    "**🛡 Reserves & Inventories** — EIA / SPR / storage and the directional read (a draw is bullish). "
    "Use the inventory figures if provided; skip if nothing new.\n"
    "**👀 On the Radar** — 2-3 near-term catalysts (data, meetings, key levels).\n\n"
    "Keep the whole brief tight and scannable — aim for ~400 words. No preamble, no sign-off."
)


def _price_line(quotes: List[Dict], spreads: List[Dict]) -> str:
    parts = ["%s %s (%+.2f%%)" % (q["label"], q["last"], q["pct"]) for q in quotes]
    parts += ["%s %.2f" % (s["label"], s["value"]) for s in spreads]
    return "; ".join(parts) if parts else "(prices unavailable)"


def _movers_line(equities: List[Dict]) -> str:
    """Broad-market quotes sorted by absolute move so the biggest movers lead."""
    if not equities:
        return ""
    ranked = sorted(equities, key=lambda q: abs(q.get("pct", 0)), reverse=True)
    return "; ".join("%s %s (%+.2f%%)" % (q["label"], q["last"], q["pct"]) for q in ranked)


def _reserves_line(eia: List[Dict]) -> str:
    if not eia:
        return ""
    return "; ".join(
        "%s %s%s (%+.1f w/w, %s)" % (e["label"], e["value"], e.get("unit", ""),
                                     e.get("change", 0), e.get("bias", "flat"))
        for e in eia
    )


def _headlines_by_category(articles: List[Dict]) -> str:
    """Group the headline context by category so Claude can build the right sections."""
    buckets: Dict[str, List[Dict]] = {}
    for a in articles:
        buckets.setdefault(a.get("category", "markets"), []).append(a)
    blocks = []
    for cat, label in _CATEGORY_LABELS:
        rows = buckets.get(cat, [])[:_PER_CATEGORY]
        if not rows:
            continue
        lines = "\n".join(
            "- [%s|%s] %s" % (r.get("impact", "neutral"), r["source_name"], r["title"])
            for r in rows
        )
        blocks.append("### %s\n%s" % (label, lines))
    return "\n\n".join(blocks) if blocks else "(no headlines available)"


def generate(articles: List[Dict], quotes: List[Dict], spreads: List[Dict],
             equities: List[Dict] = None, eia: List[Dict] = None,
             edition: str = "Morning", model: str = None) -> Dict:
    """Generate and persist the cross-asset briefing. Returns {generated_at, edition, text, model}."""
    if not available():
        raise RuntimeError("ANTHROPIC_API_KEY not set — cannot generate the briefing.")
    import anthropic

    sections = [
        "LIVE PRICES (crude/products/FX): %s" % _price_line(quotes, spreads),
    ]
    movers = _movers_line(equities)
    if movers:
        sections.append("BROAD-MARKET MOVERS (indices/megacaps, by size of move): %s" % movers)
    reserves = _reserves_line(eia)
    if reserves:
        sections.append("EIA INVENTORIES (latest, week-over-week): %s" % reserves)
    sections.append("HEADLINES (last 24h, grouped by category; [impact|source]):\n%s"
                    % _headlines_by_category(articles))
    user = "\n\n".join(sections) + "\n\nWrite the %s briefing." % edition.lower()

    resp = anthropic.Anthropic().messages.create(
        model=model or MODEL,
        max_tokens=1500,
        system=_SYSTEM.format(edition=edition.lower()),
        messages=[{"role": "user", "content": user}],
    )
    text = "".join(b.text for b in resp.content if b.type == "text").strip()
    payload = {"generated_at": datetime.now(timezone.utc).isoformat(), "edition": edition,
               "text": text, "model": model or MODEL}
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    BRIEF_PATH.write_text(json.dumps(payload), encoding="utf-8")
    return payload


_TAKE_SYSTEM = (
    "You are a senior oil-desk strategist. In 3-4 crisp sentences give the trader's read on the "
    "biggest stories right now: what's driving the tape and the bias for crude and broader risk. "
    "Trader voice — concrete, confident, no hedging. Plain text only: no markdown, no bullets, no "
    "preamble. Use only the headlines and prices provided."
)


def quick_take(headlines: List[Dict], quotes: List[Dict] = None) -> str:
    """A short live 'desk read' of the top headlines for the dashboard's analysis panel.

    Returns plain-text prose ('' if no API key). Cheap (Haiku, ~300 tokens) — the caller is
    expected to cache it so the auto-refresh doesn't re-call the API on every rerun.
    """
    if not available():
        return ""
    import anthropic

    lines = "\n".join(
        "- [%s|%s] %s" % (h.get("impact", "neutral"), h.get("source_name", ""), h["title"])
        for h in headlines[:12]
    )
    user = "PRICES: %s\n\nTOP HEADLINES:\n%s\n\nGive the desk read." % (
        _price_line(quotes or [], []), lines)
    resp = anthropic.Anthropic().messages.create(
        model=MODEL, max_tokens=300, system=_TAKE_SYSTEM,
        messages=[{"role": "user", "content": user}],
    )
    return "".join(b.text for b in resp.content if b.type == "text").strip()


def load() -> Dict:
    """Return the last stored brief, or {} if none."""
    try:
        return json.loads(BRIEF_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
