"""AI morning brief — a narrative oil-desk note generated by Claude from the day's news.

Feeds the top oil-relevant headlines + a live price/spread snapshot to Claude and asks for
a concise desk brief (snapshot, key drivers, what to watch). Stored to data/brief.json so
the dashboard can show it without re-calling the API on every load.

Requires ANTHROPIC_API_KEY (env or .env). Uses the cost-effective Haiku tier by default.
"""

import json
from datetime import datetime, timezone
from typing import Dict, List

from . import DATA_DIR
from .llm_sentiment import MODEL, available  # reuse key detection + default model

BRIEF_PATH = DATA_DIR / "brief.json"

_SYSTEM = (
    "You are a senior analyst on a crude-oil trading desk writing the morning brief. "
    "Be concise, concrete, and market-relevant — a trader reads this in 30 seconds. "
    "Use the provided live prices and headlines only; do not invent numbers. "
    "Output GitHub-flavored Markdown with exactly these sections:\n"
    "**Snapshot** — one line on where crude/products sit and the overnight move.\n"
    "**Key drivers** — 3-5 bullets, each a specific story and its bullish/bearish read for crude.\n"
    "**What to watch** — 2-3 bullets on near-term catalysts.\n"
    "No preamble, no sign-off. Keep the whole brief under ~250 words."
)


def _price_line(quotes: List[Dict], spreads: List[Dict]) -> str:
    parts = ["%s %s (%+.2f%%)" % (q["label"], q["last"], q["pct"]) for q in quotes]
    parts += ["%s %.2f" % (s["label"], s["value"]) for s in spreads]
    return "; ".join(parts) if parts else "(prices unavailable)"


def generate(articles: List[Dict], quotes: List[Dict], spreads: List[Dict], model: str = None) -> Dict:
    """Generate and persist the brief. Returns {generated_at, text, model}."""
    if not available():
        raise RuntimeError("ANTHROPIC_API_KEY not set — cannot generate the brief.")
    import anthropic

    headlines = "\n".join(
        "- [%s|%s] %s" % (a.get("impact", "neutral"), a["source_name"], a["title"])
        for a in articles[:30]
    )
    user = (
        "LIVE PRICES: %s\n\nTOP OIL-RELEVANT HEADLINES (last 24h, with keyword impact tag "
        "and source):\n%s\n\nWrite the morning brief." % (_price_line(quotes, spreads), headlines)
    )
    resp = anthropic.Anthropic().messages.create(
        model=model or MODEL,
        max_tokens=900,
        system=_SYSTEM,
        messages=[{"role": "user", "content": user}],
    )
    text = "".join(b.text for b in resp.content if b.type == "text").strip()
    payload = {"generated_at": datetime.now(timezone.utc).isoformat(), "text": text, "model": model or MODEL}
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    BRIEF_PATH.write_text(json.dumps(payload), encoding="utf-8")
    return payload


def load() -> Dict:
    """Return the last stored brief, or {} if none."""
    try:
        return json.loads(BRIEF_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
