#!/usr/bin/env python3
"""Build (and optionally email) a daily oil-desk news digest.

Renders the top oil-relevant headlines from the last N hours plus a live price snapshot
into a self-contained HTML email, saves it to reports/, and — if SMTP creds are present —
sends it. Designed to run from a GitHub Actions daily cron (serverless scheduler).

Usage:
    python tools/build_digest.py                 # build + save HTML only
    python tools/build_digest.py --fetch         # ingest fresh feeds first
    python tools/build_digest.py --email         # also send via SMTP (needs env creds)
    python tools/build_digest.py --hours 24 --top 25 --min-relevance 30

Email config (env vars, e.g. from .env or GitHub secrets):
    SMTP_HOST (default smtp.gmail.com), SMTP_PORT (default 587),
    SMTP_USER, SMTP_PASS, DIGEST_TO (comma-separated), DIGEST_FROM (default SMTP_USER)
"""

import argparse
import html
import os
import smtplib
import sys
from datetime import datetime, timedelta, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src"))

from newsdash import REPO_ROOT  # noqa: E402
from newsdash import db, ingest, prices  # noqa: E402

try:
    from dotenv import load_dotenv  # noqa: E402
    load_dotenv(REPO_ROOT / ".env")
except Exception:
    pass


def _recent(rows, hours):
    cutoff = datetime.now(timezone.utc) - timedelta(hours=hours)
    out = []
    for r in rows:
        ts = r.get("published_at") or r.get("fetched_at")
        try:
            dt = datetime.fromisoformat(ts)
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)
        except (TypeError, ValueError):
            continue
        if dt >= cutoff:
            out.append(r)
    return out


def _impact_badge(r):
    if r.get("impact") == "bullish":
        return '<span style="background:#16c784;color:#04130d;border-radius:4px;padding:1px 6px;font-size:11px;font-weight:700">BULLISH %+d</span>' % r.get("impact_score", 0)
    if r.get("impact") == "bearish":
        return '<span style="background:#ea3943;color:#fff;border-radius:4px;padding:1px 6px;font-size:11px;font-weight:700">BEARISH %d</span>' % r.get("impact_score", 0)
    return ""


def render_html(articles, quotes, hours):
    today = datetime.now(timezone.utc).strftime("%A %d %B %Y")
    # price tape
    tape = ""
    for q in quotes:
        color = "#16c784" if q["dir"] == "up" else "#ea3943" if q["dir"] == "down" else "#7d8b9a"
        arrow = "&#9650;" if q["dir"] == "up" else "&#9660;" if q["dir"] == "down" else "&#9632;"
        tape += (
            '<td style="padding:8px 14px;border:1px solid #1e2733;border-radius:8px">'
            '<div style="color:#7d8b9a;font-size:10px;text-transform:uppercase">%s</div>'
            '<div style="font-size:17px;font-weight:800;color:#e6edf3">%s</div>'
            '<div style="color:%s;font-size:12px;font-weight:700">%s %+.2f%%</div></td>'
            % (html.escape(q["label"]), q["last"], color, arrow, q["pct"])
        )
    rows = ""
    for r in articles:
        badge = _impact_badge(r)
        rows += (
            '<tr><td style="padding:10px 0;border-bottom:1px solid #1e2733">'
            '<a href="%s" style="color:#e6edf3;text-decoration:none;font-weight:600;font-size:15px">%s</a>'
            '<div style="margin-top:4px;color:#7d8b9a;font-size:12px">'
            '<span style="color:#9fb2c4;font-weight:600">%s</span> &middot; '
            '<span style="color:#ffa45c">relevance %d</span> %s</div>'
            '</td></tr>'
            % (html.escape(r["url"]), html.escape(r["title"]),
               html.escape(r["source_name"]), r["relevance"],
               (" &middot; " + badge) if badge else "")
        )
    return """\
<!DOCTYPE html><html><body style="margin:0;background:#0b0f14;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif">
<div style="max-width:680px;margin:0 auto;padding:24px;background:#0b0f14;color:#e6edf3">
  <div style="font-size:22px;font-weight:800">&#128739; Oil Desk &mdash; Daily News Digest</div>
  <div style="color:#7d8b9a;font-size:13px;margin-bottom:16px">%s &middot; top %d stories, last %dh</div>
  <table cellspacing="6" style="border-collapse:separate;margin-bottom:18px"><tr>%s</tr></table>
  <table width="100%%" cellspacing="0" cellpadding="0">%s</table>
  <div style="color:#5b6b7a;font-size:11px;margin-top:20px">
    Generated by the News Dashboard &middot; oil-relevance &amp; crude-impact tagging are heuristic hints, not advice.
  </div>
</div></body></html>""" % (today, len(articles), hours, tape, rows)


def send_email(html_body, subject):
    host = os.environ.get("SMTP_HOST", "smtp.gmail.com")
    port = int(os.environ.get("SMTP_PORT", "587"))
    user = os.environ.get("SMTP_USER")
    pw = os.environ.get("SMTP_PASS")
    to = os.environ.get("DIGEST_TO")
    sender = os.environ.get("DIGEST_FROM", user)
    if not (user and pw and to):
        print("Email skipped: set SMTP_USER, SMTP_PASS and DIGEST_TO to enable sending.")
        return False
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = to
    msg.attach(MIMEText(html_body, "html"))
    with smtplib.SMTP(host, port, timeout=30) as s:
        s.starttls()
        s.login(user, pw)
        s.sendmail(sender, [a.strip() for a in to.split(",")], msg.as_string())
    print("Email sent to %s" % to)
    return True


def main():
    ap = argparse.ArgumentParser(description="Build/send the daily oil-desk digest.")
    ap.add_argument("--fetch", action="store_true", help="Ingest fresh feeds first.")
    ap.add_argument("--email", action="store_true", help="Send via SMTP (needs env creds).")
    ap.add_argument("--hours", type=int, default=24)
    ap.add_argument("--top", type=int, default=25)
    ap.add_argument("--min-relevance", type=int, default=25)
    args = ap.parse_args()

    if args.fetch:
        s = ingest.run_once()
        print("Fetched: %d new, %d/%d sources ok" % (s["new"], s["ok"], s["sources"]))

    pool = db.query_articles(limit=500, min_relevance=args.min_relevance)
    articles = _recent(pool, args.hours)
    articles.sort(key=lambda r: r["relevance"], reverse=True)
    articles = articles[: args.top]
    quotes = prices.get_quotes()

    body = render_html(articles, quotes, args.hours)
    reports = REPO_ROOT / "reports"
    reports.mkdir(exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d")
    out = reports / ("digest-%s.html" % stamp)
    out.write_text(body, encoding="utf-8")
    print("Digest written: %s (%d stories)" % (out, len(articles)))

    if args.email:
        subject = "Oil Desk Digest — %s (%d stories)" % (
            datetime.now(timezone.utc).strftime("%d %b"), len(articles))
        send_email(body, subject)


if __name__ == "__main__":
    main()
